name: flutter_application_1
description: "اپ عاشقونه - تماشای همزمان، چت، تقویم و پریود"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.3.3 

  

  # 📱 State Management
  provider: ^6.1.1

  # 💾 Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 🌐 Network & API
  http: ^1.2.0
  web_socket_channel: ^3.0.1

  # 🎬 Video & Media
  video_player: ^2.10.0
  image_picker: ^1.1.2
  file_picker: ^8.1.4

  # 📅 Calendar (Persian)
  shamsi_date: ^1.0.4

  persian_datetime_picker: ^3.2.0
  

  # 📍 Location
  geolocator: ^13.0.1

  # 🎨 Animations & UI
  lottie: ^3.3.2
  shimmer: ^3.0.0

  # 📸 Camera
  camera: ^0.11.1


  pinput: ^3.0.1

  # 🔊 Audio
  # just_audio: ^0.9.46

  # 📱 Device Info
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0

  # 🔗 Deep Linking (جایگزین uni_links)
  #app_links: ^7.0.0

  # 📤 Share
  share_plus: ^10.1.2

  # 🌍 Localization
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^7.0.0
  animated_emoji: ^3.2.1
  flutter_image_compress: ^2.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/lottie/female_avatar.json
    - assets/lottie/male_avatar.json
    
  fonts:
    - family: titr
      fonts:
        - asset: fonts/ITitrBd.ttf
    - family: titr1
      fonts:
        - asset: fonts/BTitrBd.ttf
    - family: Vazir
      fonts:
        - asset: fonts/VazirBold.ttf